### ISSUE TITLE
Disallow structs as mixin implementations and targets

### ISSUE THREAD

**Issue by rileywhite** [rileywhite/Cilador#6]
Specifically test mixin implementations and targets to ensure that they are not value types. Allow nested value types within the mixin implementation, however.

**Comment by aniongithub** [comment]
Why disallow structs from Mixins? Structs implementing interfaces actually are very performant in C# and lot of GPU programming needs arrays of structures. In these cases, having a mixin that can implement canned behaviors on these structures are very desirable.

**Comment by rileywhite** [comment]
I agree this could be useful. It was more of a pragmatic decision at the time, though.

I appreciate your interest.
